// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAYfkOej7yzr7fjht4r07NVQe0DU43Gerk',
//     appId: '1:263362389093:web:e9827dbe99b0753bf6128c',
//     messagingSenderId: '263362389093',
//     projectId: 'lock-bd2ac',
//     authDomain: 'lock-bd2ac.firebaseapp.com',
//     storageBucket: 'lock-bd2ac.appspot.com',
//     measurementId: 'G-T1CH8XBE51',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBQ3nmO5qH4L1iCItUFGwpHRCv5oQIOAjM',
//     appId: '1:263362389093:android:cc7c2591b3152347f6128c',
//     messagingSenderId: '263362389093',
//     projectId: 'lock-bd2ac',
//     storageBucket: 'lock-bd2ac.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyD7qaSDqIz8GOc8zpw8b907ByhXtGt-VUg',
//     appId: '1:263362389093:ios:0e17908c14af66bbf6128c',
//     messagingSenderId: '263362389093',
//     projectId: 'lock-bd2ac',
//     storageBucket: 'lock-bd2ac.appspot.com',
//     iosBundleId: 'com.example.universityAttendance',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyD7qaSDqIz8GOc8zpw8b907ByhXtGt-VUg',
//     appId: '1:263362389093:ios:0e17908c14af66bbf6128c',
//     messagingSenderId: '263362389093',
//     projectId: 'lock-bd2ac',
//     storageBucket: 'lock-bd2ac.appspot.com',
//     iosBundleId: 'com.example.universityAttendance',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyAYfkOej7yzr7fjht4r07NVQe0DU43Gerk',
//     appId: '1:263362389093:web:e9f507133072273ff6128c',
//     messagingSenderId: '263362389093',
//     projectId: 'lock-bd2ac',
//     authDomain: 'lock-bd2ac.firebaseapp.com',
//     storageBucket: 'lock-bd2ac.appspot.com',
//     measurementId: 'G-1KW8ZVWPDS',
//   );
// }
