
default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
      app: "1:263362389093:android:cc7c2591b3152347f6128c",
      firebase_cli_token: "1//03pvcaycYA5uUCgYIARAAGAMSNwF-L9IrTAXHxBzrB_OPHh4uuhfyajdVW0GNwdhT2lgrZke76Fmylwh2CVX0-rucrgb1UhZwJy0",
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      testers: "gosama481@gmail.com",
      release_notes: "First Fastlane Firebase Distribution"
      
  )
  end
end
